trigger:
- dev  # or your branch name, e.g. dev

pool:
  name: Default  # your self-hosted agent pool name

steps:
- script: |
    echo "Hello from Azure Pipeline!"
    pwd
    ls -l
    whoami
    sudo docker stop web 
    sudo docker rm web
    sudo docker run -d -p 80:80 --name web python-app:latest
  displayName: 'Run simple shell commands'
